export const BodyCollections = {
  body1: {
    heading: "New Arrival",
    subHeading: "Discover Our New Collections",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis.",
    productImage: [
      {
        id: 1,
        image: "images/banner-body1.png",
      },
    ],
    button: { text: "BUY NOW" },
    template_Id: 1,
  },
  body2: {
    heading: "Browse The Range",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    productImage: [
      { id: 1, image: "Dining Image", text: "Dining" },
      { id: 2, image: "Living Image", text: "Living" },
      { id: 3, image: "Bedroom Image", text: "Bedroom" },
    ],
    template_Id: 2,
  },
  body3: {
    heading: "50+ Beautiful rooms inspiration",
    description:
      "Our designer already made a lot of beautiful prototype of rooms that inspire you",
    button: { text: "Explore More" },
    productImage: [
      { id: 1, image: "carousel Image 1", text: "Image 1 Text" },
      { id: 2, image: "carousel Image 2", text: "Image 2 Text" },
      { id: 3, image: "carousel Image 3", text: "Image 3 Text" },
      { id: 4, image: "carousel Image 4", text: "Image 4 Text" },
    ],
    template_Id: 3,
  },
  body4: {
    heading: "Our Products",
    button: { text: "Show More" },
    productImage: [
      {
        id: 1,
        image: "Syltherine Image",
        text: "Syltherine",
        subText: "Stylish cafe chair",
        price: "Rp 2.500.000",
      },
      {
        id: 2,
        image: "Leviosa Image",
        text: "Leviosa",
        subText: "Stylish cafe chair",
        price: "Rp 2.500.000",
      },
      {
        id: 3,
        image: "Lolito Image",
        text: "Lolito",
        subText: "Luxury big sofa",
        price: "Rp 2.500.000",
      },
      {
        id: 4,
        image: "Respira Image",
        text: "Respira",
        subText: "Outdoor bar table and stool",
        price: "Rp 500.000",
      },
      {
        id: 5,
        image: "Grifo Image",
        text: "Grifo",
        subText: "Night lamp",
        price: "Rp 1.500.000",
      },
      {
        id: 6,
        image: "Muggo Image",
        text: "Muggo",
        subText: "Small mug",
        price: "Rp 150.000",
      },
      {
        id: 7,
        image: "Pingky Image",
        text: "Pingky",
        subText: "Cute bed set",
        price: "Rp 7.000.000",
      },
      {
        id: 8,
        image: "Potty Image",
        text: "Potty",
        subText: "Minimalist flower pot",
        price: "Rp 500.000",
      },
      {
        id: 9,
        image: "Syltherine Image",
        text: "Syltherine",
        subText: "Stylish cafe chair",
        price: "Rp 2.500.000",
      },
      {
        id: 10,
        image: "Leviosa Image",
        text: "Leviosa",
        subText: "Stylish cafe chair",
        price: "Rp 2.500.000",
      },
      {
        id: 11,
        image: "Lolito Image",
        text: "Lolito",
        subText: "Luxury big sofa",
        price: "Rp 2.500.000",
      },
      {
        id: 12,
        image: "Respira Image",
        text: "Respira",
        subText: "Outdoor bar table and stool",
        price: "Rp 500.000",
      },
      {
        id: 13,
        image: "Grifo Image",
        text: "Grifo",
        subText: "Night lamp",
        price: "Rp 1.500.000",
      },
      {
        id: 14,
        image: "Muggo Image",
        text: "Muggo",
        subText: "Small mug",
        price: "Rp 150.000",
      },
      {
        id: 15,
        image: "Pingky Image",
        text: "Pingky",
        subText: "Cute bed set",
        price: "Rp 7.000.000",
      },
      {
        id: 16,
        image: "Potty Image",
        text: "Potty",
        subText: "Minimalist flower pot",
        price: "Rp 500.000",
      },
      {
        id: 17,
        image: "Syltherine Image",
        text: "Syltherine",
        subText: "Stylish cafe chair",
        price: "Rp 2.500.000",
      },
      {
        id: 18,
        image: "Leviosa Image",
        text: "Leviosa",
        subText: "Stylish cafe chair",
        price: "Rp 2.500.000",
      },
      {
        id: 19,
        image: "Lolito Image",
        text: "Lolito",
        subText: "Luxury big sofa",
        price: "Rp 2.500.000",
      },
      {
        id: 20,
        image: "Respira Image",
        text: "Respira",
        subText: "Outdoor bar table and stool",
        price: "Rp 500.000",
      },
      {
        id: 21,
        image: "Grifo Image",
        text: "Grifo",
        subText: "Night lamp",
        price: "Rp 1.500.000",
      },
      {
        id: 22,
        image: "Muggo Image",
        text: "Muggo",
        subText: "Small mug",
        price: "Rp 150.000",
      },
      {
        id: 23,
        image: "Pingky Image",
        text: "Pingky",
        subText: "Cute bed set",
        price: "Rp 7.000.000",
      },
      {
        id: 24,
        image: "Potty Image",
        text: "Potty",
        subText: "Minimalist flower pot",
        price: "Rp 500.000",
      },
      {
        id: 25,
        image: "Syltherine Image",
        text: "Syltherine",
        subText: "Stylish cafe chair",
        price: "Rp 2.500.000",
      },
      {
        id: 26,
        image: "Leviosa Image",
        text: "Leviosa",
        subText: "Stylish cafe chair",
        price: "Rp 2.500.000",
      },
      {
        id: 27,
        image: "Lolito Image",
        text: "Lolito",
        subText: "Luxury big sofa",
        price: "Rp 2.500.000",
      },
      {
        id: 28,
        image: "Respira Image",
        text: "Respira",
        subText: "Outdoor bar table and stool",
        price: "Rp 500.000",
      },
      {
        id: 29,
        image: "Grifo Image",
        text: "Grifo",
        subText: "Night lamp",
        price: "Rp 1.500.000",
      },
      {
        id: 30,
        image: "Muggo Image",
        text: "Muggo",
        subText: "Small mug",
        price: "Rp 150.000",
      },
      {
        id: 31,
        image: "Pingky Image",
        text: "Pingky",
        subText: "Cute bed set",
        price: "Rp 7.000.000",
      },
      {
        id: 32,
        image: "Potty Image",
        text: "Potty",
        subText: "Minimalist flower pot",
        price: "Rp 500.000",
      },
      {
        id: 33,
        image: "Syltherine Image",
        text: "Syltherine",
        subText: "Stylish cafe chair",
        price: "Rp 2.500.000",
      },
      {
        id: 34,
        image: "Leviosa Image",
        text: "Leviosa",
        subText: "Stylish cafe chair",
        price: "Rp 2.500.000",
      },
      {
        id: 35,
        image: "Lolito Image",
        text: "Lolito",
        subText: "Luxury big sofa",
        price: "Rp 2.500.000",
      },
      {
        id: 36,
        image: "Respira Image",
        text: "Respira",
        subText: "Outdoor bar table and stool",
        price: "Rp 500.000",
      },
      {
        id: 37,
        image: "Grifo Image",
        text: "Grifo",
        subText: "Night lamp",
        price: "Rp 1.500.000",
      },
      {
        id: 38,
        image: "Muggo Image",
        text: "Muggo",
        subText: "Small mug",
        price: "Rp 150.000",
      },
      {
        id: 39,
        image: "Pingky Image",
        text: "Pingky",
        subText: "Cute bed set",
        price: "Rp 7.000.000",
      },
      {
        id: 40,
        image: "Potty Image",
        text: "Potty",
        subText: "Minimalist flower pot",
        price: "Rp 500.000",
      },
      {
        id: 41,
        image: "Syltherine Image",
        text: "Syltherine",
        subText: "Stylish cafe chair",
        price: "Rp 2.500.000",
      },
      {
        id: 42,
        image: "Leviosa Image",
        text: "Leviosa",
        subText: "Stylish cafe chair",
        price: "Rp 2.500.000",
      },
      {
        id: 43,
        image: "Lolito Image",
        text: "Lolito",
        subText: "Luxury big sofa",
        price: "Rp 2.500.000",
      },
      {
        id: 44,
        image: "Respira Image",
        text: "Respira",
        subText: "Outdoor bar table and stool",
        price: "Rp 500.000",
      },
      {
        id: 45,
        image: "Grifo Image",
        text: "Grifo",
        subText: "Night lamp",
        price: "Rp 1.500.000",
      },
      {
        id: 46,
        image: "Muggo Image",
        text: "Muggo",
        subText: "Small mug",
        price: "Rp 150.000",
      },
      {
        id: 47,
        image: "Pingky Image",
        text: "Pingky",
        subText: "Cute bed set",
        price: "Rp 7.000.000",
      },
      {
        id: 48,
        image: "Potty Image",
        text: "Potty",
        subText: "Minimalist flower pot",
        price: "Rp 500.000",
      },
    ],
    template_Id: 4,
  },
};
